<a href="https://colab.research.google.com/github/19PA1A0222/AI-Lab/blob/master/Exp_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Experiment No 1:Numpy

## 1) Differentways to create a Numpy arrays.

###a)Create a numpy array using list

In [ ]:
import numpy as np
a = np.array([2,3,4])
print(a)

[2 3 4]


###b)Create a numpy array using arange

In [ ]:
b = np.arange(8)
print(b)

[0 1 2 3 4 5 6 7]


## 2)Add,remove,modify elements in a array

### a)Add

In [ ]:
s = np.append(a,[2,5,7])
print(s)

[2 3 4 2 5 7]


### b)Remove

In [ ]:
p = np.delete(a,2)
print(p)

[2 3]


### c)Modify

In [ ]:
s = np.array([6,4,3,1,9,5])
s[s<2]=-1
print(s)

[ 6  4  3 -1  9  5]


## 3)Arthematic operations on Numpy array.

###a) Add

In [1]:
 
import numpy as np
t = np.random.random((3,3))
r = np.random.random((3,3))
add = np.add(t,r)
 
print(add)

[[1.82487078 0.98547183 0.42770924]
 [1.187468   1.38272672 1.18904154]
 [0.33512657 0.43310275 1.52364176]]


###b) Subtract

In [3]:
sub = np.subtract(t,r)
print(sub)

[[ 0.0855581  -0.8680213  -0.20157676]
 [ 0.00957162  0.30972335 -0.68744112]
 [ 0.16426743 -0.03437786  0.35734173]]


###C) Multiply

In [4]:
prod = np.multiply(t,r)
print(prod)

[[0.8307083  0.05442344 0.0355755 ]
 [0.35249716 0.45400116 0.23531113]
 [0.02133151 0.04659904 0.54844778]]


###d) Mod

In [5]:
mod = np.mod(t,r)
print(mod)

[[0.0855581  0.05872527 0.11306624]
 [0.00957162 0.30972335 0.25080021]
 [0.07883787 0.19936244 0.35734173]]


###e) Power

In [6]:
pow = np.power(t,r)
print(pow)

[[0.96093631 0.07227911 0.50366044]
 [0.73911293 0.91431542 0.27316472]
 [0.8882215  0.68595942 0.9648548 ]]


## 4)Slicing and iterating of numpy arrays.

### a)slicing

In [ ]:
 
import numpy as np
arr = np.array([7,5,3,9,2,5])
print(arr[2:5])

[3 9 2]


### b) iterating

In [ ]:
 
for x in arr:
  print(x)

7
5
3
9
2
5


## 5)Matrix operation on numpy arrays.

In [ ]:
 
import numpy as np
d = np.array([[4,3],[2,1]])
v = np.array([[8,7],[6,5]])
print(np.add(d,v))
print(np.subtract(d,v))    
print(np.divide(d,v))

[[12 10]
 [ 8  6]]
[[-4 -4]
 [-4 -4]]
[[0.5        0.42857143]
 [0.33333333 0.2       ]]
